version: '3.3'

services:

  theia-cv:
    container_name: theia-cv
    image: ghokun/theia-cv:v1.47.1
    depends_on:
      - novnc
    environment:
      - DISPLAY=novnc:0.0 
    volumes:
      - '$source_code_path:/home/project:cached'
      - '~/.ssh:/home/theia/.ssh'
    ports:
      - '3000:3000'
    networks:
      - x11
    restart: unless-stopped
      
  novnc:
    container_name: novnc
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=800
      - RUN_XTERM=no
      - RUN_FLUXBOX=yes
    ports:
      - "8080:8080"
    networks:
      - x11
    restart: unless-stopped

  rstudio:
    container_name: rstudio
    image: rocker/rstudio
    environment:
      - PASSWORD=yourpasswordhere
    networks:
      - x11
    ports:
      - 8787:8787
    volumes:
      - '$source_code_path:/home/rstudio'
    restart: unless-stopped

networks:
  x11:
