version: '3.3'
services:
  theia-cv:
    container_name: theia-cv
    environment:
      - 'DISPLAY=$ip:0' 
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '$source_code_path:/home/project:cached'
    ports:
      - '3000:3000'
    image: ghokun/theia-cv
