name: dockerhub

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/workflows/*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build next image
        run: docker build --build-arg version=next --build-arg strip=true  -t ghokun/theia-cv:next .

      - name: Log into registry
        run: echo "${{ secrets.dockerhub }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          docker push ghokun/theia-cv:next
