name: dockerhub

on:
  push:
    tags:
      - v*
    paths-ignore:
      - README.md
      - .github/workflows/*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build tagged image
        run: docker build --build-arg strip=true  -t ghokun/theia-cv:${{ github.event.release.tag_name }} .

      - name: Log into registry
        run: echo "${{ secrets.dockerhub }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          docker push ghokun/theia-cv:${{ github.event.release.tag_name }}
